### ISSUE TITLE
returned data delayed by one request.

### ISSUE THREAD

**Issue by peter64** [felipecruz/pyaio#6]
I am using Ubuntu 12.04 and Python 2.7.3 with your 0.3 version software.
I will paste a console trace below to illustrate my point.

Python 2.7.3 (default, Aug  1 2012, 05:14:39)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import sys
> > > sys.path.insert(0, 'pyaio-0.3-py2.7-linux-x86_64.egg')
> > > import pyaio
> > > import os
> > > def aio_callback(buf, rcode, errno):
> > > ...     if rcode > 0:
> > > ...         print 'python callback "%s"' % buf
> > > ...     elif rcode == 0:
> > > ...         print "EOF"
> > > ...     else:
> > > ...         print "Error: %d" % errno
> > > ...
> > > 
> > > fd = os.open('/tmp/pyaio.txt', os.O_RDONLY)
> > > pyaio.aio_read(fd, 10, 10, aio_callback)
> > > 0
> > > pyaio.aio_read(fd, 10, 20, aio_callback)
> > > python callback "nchronous "
> > > 0
> > > pyaio.aio_read(fd, 10, 30, aio_callback)
> > > python callback "nchronous I/O bindin"
> > > 0
> > > pyaio.aio_read(fd, 10, 20, aio_callback)
> > > python callback "nchronous I/O bindings (aio.h)"
> > > 0
> > > pyaio.aio_read(fd, 10, 10, aio_callback)
> > > python callback "nchronous I/O bindin"
> > > 0
> > > pyaio.aio_read(fd, 20, 10, aio_callback)
> > > python callback "nchronous "
> > > 0
> > > pyaio.aio_read(fd, 20, 20, aio_callback)
> > > python callback "I/O bindin"
> > > 0
> > > pyaio.aio_read(fd, 20, 30, aio_callback)
> > > python callback "I/O bindings (aio.h)"
> > > 0

If I can provide further details just let me know. Thanks.

**Comment by felipecruz** [comment]
Hi!

What do you mean by "delayed by one request"? you mean, the program ends before last callback be executed?

regards,

**Comment by peter64** [comment]
Hey Filipe, 

Thanks for getting back to me.
Yeah basically that's what I mean.
As you can see from the above commands, my first executed command returned nothing after approximately 1 second.

pyaio.aio_read(fd, 10, 10, aio_callback)
0 ### nothing returned

The second command returned what the first should have returned.

pyaio.aio_read(fd, 10, 20, aio_callback)
python callback "nchronous " ### note 10 chars here not 20
0

The final call never returned it's own result, just the one of the call before.
Let me know if I can help with anything else. Thanks.

**Comment by felipecruz** [comment]
Hi @peter64 

Are you running those commands in the interactive mode? I'm not sure if this can trigger some odd behavior..

Can you run this script (above) and post the results here?
Also, remember that if you dont sleep `time.sleep(0.5)` your program might end before all callbacks calls.

``` python
import pyaio
import time
import os

f = open('/tmp/pyaio.txt', 'wt')
f.write('Python aio.h Async IO Bindings')
f.close()

def aio_callback(buf, rcode, errno):
    if rcode > 0:
        print 'python callback "%s"' % buf
    elif rcode == 0:
        print "EOF"
    else:
        print "Error: %d" % errno

fd = os.open('/tmp/pyaio.txt', os.O_RDONLY)

pyaio.aio_read(fd, 10, 20, aio_callback)

pyaio.aio_read(fd, 10, 30, aio_callback)

pyaio.aio_read(fd, 10, 20, aio_callback)

pyaio.aio_read(fd, 10, 10, aio_callback)

pyaio.aio_read(fd, 20, 10, aio_callback)

pyaio.aio_read(fd, 20, 20, aio_callback)

pyaio.aio_read(fd, 20, 30, aio_callback)

time.sleep(0.5)
```

**Comment by peter64** [comment]
Worked like a charm! I guess it was just the fact I was running in interactive mode, sorry about the false alarm.

python pyaio-test.py
python callback ".h Async IO Bindings"
python callback ".h Async IO Bindings"
python callback ".h Async IO Bindings"
python callback ".h Async I"
python callback "O Bindings"
python callback "O Bindings"
python callback "O Bindings"

python pyaio-test.py
python callback ".h Async IO Bindings"
python callback ".h Async IO Bindings"
python callback ".h Async IO Bindings"
python callback "O Bindings"
python callback ".h Async I"
python callback "O Bindings"
python callback "O Bindings"

python pyaio-test.py
python callback ".h Async IO Bindings"
python callback ".h Async IO Bindings"
python callback ".h Async IO Bindings"
python callback "O Bindings"
python callback "O Bindings"
python callback ".h Async I"
python callback "O Bindings"

**Comment by felipecruz** [comment]
Great! :) 

Let me know if you find another strange behavior.

I'm closing now.
