### ISSUE TITLE
0.4?

### ISSUE THREAD

**Issue by icgood** [felipecruz/pyaio#7]
Is anything keeping this project from bumping to the next version?  I'm getting SEGFAULTs with 0.3 installed from PyPI, but not when installing from the master branch.

**Comment by icgood** [comment]
Segfault was passing a `memoryview` into `aio_write()` instead of a regular `str`. Works correctly in master branch, but not tag 0.3.

**Comment by felipecruz** [comment]
Hi @icgood

Version bumped to 0.4 to match latest code from master.

Thanks
